"use strict";
module.exports = {
  config: {
    hyperTransparent: {
      opacity: 0.8,
      vibrancy: "dark", // ['', 'dark', 'medium-light', 'ultra-dark']
    },
    updateChannel: "stable",
    fontSize: 18,
    fontFamily: "FiraCode Nerd Font Ret",
    fontLigatures: true,
    fontWeight: "normal",
    fontWeightBold: "bold",
    lineHeight: 1.15,
    letterSpacing: 0,
    cursorColor: "#FFFFFF",
    cursorAccentColor: "#000",
    cursorShape: "BLOCK",
    cursorBlink: true,
    foregroundColor: "#fff",
    backgroundColor: "#202020",
    selectionColor: "rgba(255,255,255,0.3)",
    borderColor: "#545454",
    css: "",
    termCSS: "",
    workingDirectory: "",
    showHamburgerMenu: "",
    showWindowControls: "",
    padding: "12px 14px",
    colors: {
      black: "#282C34",
      red: "#EA5B76",
      green: "#98C379",
      yellow: "#FED552",
      blue: "#6495CF",
      magenta: "#C678DD",
      cyan: "#56B6C2",
      white: "#DCDFE4",
      lightBlack: "#5A6374",
      lightRed: "#E06C75",
      lightGreen: "#98C379",
      lightYellow: "#E5C07B",
      lightBlue: "#61AFEF",
      lightMagenta: "#C678DD",
      lightCyan: "#56B6C2",
      lightWhite: "#DCDFE4",
      cursorColor: "#FFFFFF",
      cursorAccentColor: "#FFFFFF",
      selectionColor: "#FFFFFF",
    },
    shell: "",
    shellArgs: ["--login"],
    env: {},
    bell: "SOUND",
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: "vertical",
    webGLRenderer: true,
    webLinksActivationKey: "",
    disableLigatures: false,
    disableAutoUpdates: false,
    screenReaderMode: false,
    preserveCWD: true,
    // backgroundImage: "/Users/lturret/Pictures/other/kirin_terminal.png",
  },
  plugins: ["hyper-transparent"],
  localPlugins: [],
  keymaps: {},
};
